services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://mongo:27017/chatdb
      REDIS_URI: redis://redis:6379
      PORT: 8080
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine

volumes:
  mongo_data:
